---

- name: Reboot OpenWRT APs
  hosts: openwrt
  become: false
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: 'root'

  tasks:
    - name: Applying config (only when tag 'apply')
      ansible.builtin.raw: 'uci commit'
      tags: [apply, never]

    - name: Rebooting
      ansible.builtin.raw: 'reboot'
      tags: apply
